version: 2

defaults: &defaults
  docker:
  - image: circleci/node:10.12-browsers

build-defaults: &build-defaults
  <<: *defaults
  steps:
  - checkout
  - restore_cache:
      key: node_modules-{{ checksum "package-lock.json" }}
  - run: npm run $CIRCLE_JOB
  - run:
      name: Compress artifact
      command: |
        VERSION=`node -p "require('./package.json').version"`
        MULTILINED_JOB_NAME=`echo $CIRCLE_JOB|perl -pe 's/-/\n/g'`
        OS_NAME=`echo $MULTILINED_JOB_NAME | sed -n 2p`
        ARCHITECTURE=`echo $MULTILINED_JOB_NAME | sed -n 3p`
        ARTIFACT_NAME=treesizer-$VERSION-`echo $CIRCLE_JOB|sed 's/^build-//g'`

        mkdir artifacts

        if [ $OS_NAME='win' ]; then
          ARTIFACT_PATH=artifacts/$ARTIFACT_NAME.zip
          zip -r $ARTIFACT_PATH dist/$ARTIFACT_NAME
        else
          ARTIFACT_PATH=artifacts/$ARTIFACT_NAME.tar.gz
          tar -zcfr $ARTIFACT_PATH -r dist/$ARTIFACT_NAME
        fi

  - persist_to_workspace:
      root: artifacts
      paths:
      - ./*
jobs:
  prepare:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        key: node_modules-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: if [ ! -d node_modules ]; then npm ci; fi
    - save_cache:
        key: node_modules-{{ checksum "package-lock.json" }}
        paths:
        - node_modules

  build-mac-x64:
    <<: *build-defaults

  build-win-x86:
    <<: *build-defaults

  build-win-x64:
    <<: *build-defaults

  build-linux-x86:
    <<: *build-defaults

  build-linux-x64:
    <<: *build-defaults

  deploy:
    <<: *defaults
    steps:
    - attach_workspace:
        at: artifacts
    - run: ls artifacts

workflows:
  version: 2
  deploy:
    jobs:
    - prepare
    - build-win-x86:
        requires:
        - prepare
    - build-win-x64:
        requires:
        - prepare
    - build-mac-x64:
        requires:
        - prepare
    - build-linux-x86:
        requires:
        - prepare
    - build-linux-x64:
        requires:
        - prepare
    - deploy:
        requires:
        - build-win-x86
        - build-win-x64
        - build-mac-x64
        - build-linux-x86
        - build-linux-x64
