version: 2
jobs:
  build-and-test:
    docker:
    - image: node:10.12-alpine
    steps:
    - checkout
    - run: npm ci
    - run: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
    - build-and-test