version: 2

defaults: &defaults
  docker:
  - image: enfunctor/nwjs-builder
    environment:
      CONFIG_VERSION: 1

_steps:
  save_cache: &save_cache_node_modules
      name: Saving node_modules as cache
      key: node_modules-{{ arch }}-{{ .Environment.CONFIG_VERSION }}-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}-{{ checksum "package-lock.json" }}
      paths:
      - node_modules

  restore_cache: &restore_cache_node_modules
      name: Restoring cached node_modules
      key: node_modules-{{ arch }}-{{ .Environment.CONFIG_VERSION }}-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}-{{ checksum "package-lock.json" }}

build-defaults: &build-defaults
  <<: *defaults
  steps:
  - checkout
  - restore_cache: *restore_cache_node_modules
  - run:
      name: Generate .NW_BUILD_VERSION
      command: |
        echo `node -pe "require('./package.json').build.nwVersion"` > .NW_BUILD_VERSION
        echo NW_BUILD_VERSION is `cat .NW_BUILD_VERSION`
  - restore_cache:
      name: Restoring builder cache
      key: nwjs_builder-{{ arch }}-{{ .Environment.CONFIG_VERSION }}-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".NW_BUILD_VERSION" }}
  - run:
      name: Build
      command: npm run $CIRCLE_JOB
  - save_cache:
      name: Saving builder cache
      key: nwjs_builder-{{ arch }}-{{ .Environment.CONFIG_VERSION }}-{{ .Environment.CIRCLE_WORKING_DIRECTORY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".NW_BUILD_VERSION" }}
      paths:
      - ~/.nwjs-builder/caches

  - run:
      name: Compress artifacts
      command: |
        VERSION=`node -p "require('./package.json').version"`
        OS_NAME=`node -p "'$CIRCLE_JOB'.match(/build-(\w+)/)[1]"`
        ARTIFACT_NAME=treesizer-$VERSION-`echo $CIRCLE_JOB|sed 's/^build-//g'`

        mkdir artifacts

        pushd dist
        for DIST_ENTRY in *; do
          if [ $OS_NAME='win' ]; then
            zip -r ../artifacts/$DIST_ENTRY.zip $DIST_ENTRY
          else
            tar -zcfr ../artifacts/$DIST_ENTRY.tar.gz $DIST_ENTRY
          fi
        done
        popd

  - persist_to_workspace:
      root: artifacts
      paths:
      - ./*
jobs:
  prepare:
    <<: *defaults
    steps:
    - checkout
    - restore_cache: *restore_cache_node_modules
    - run:
        name: Install dependencies
        command: if [ ! -d node_modules ]; then npm ci; fi
    - save_cache: *save_cache_node_modules

  build-mac:
    <<: *build-defaults

  build-win:
    <<: *build-defaults

  build-linux:
    <<: *build-defaults

  deploy:
    <<: *defaults
    steps:
    - attach_workspace:
        at: artifacts
    - run: ls artifacts

workflows:
  version: 2
  deploy:
    jobs:
    - prepare
    - build-win:
        requires:
        - prepare
    - build-mac:
        requires:
        - prepare
    - build-linux:
        requires:
        - prepare
    - deploy:
        requires:
        - build-win
        - build-mac
        - build-linux
